//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class animal_shelterEntities : DbContext
    {
        public animal_shelterEntities()
            : base("name=animal_shelterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<aviary> aviaries { get; set; }
        public virtual DbSet<aviary_animal> aviary_animal { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Clerk_Zone> Clerk_Zone { get; set; }
        public virtual DbSet<ClimatZone> ClimatZones { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<FeedType> FeedTypes { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Zone_Animal> Zone_Animal { get; set; }
    }
}
